---

kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: python:3.6
    environment:
      POETRY_PYPI_TOKEN_PYPI:
        from_secret: poetry_pypi_token
    commands:
      - pip install poetry
      - poetry config repositories.testpypi https://test.pypi.org/legacy/
      - poetry config pypi-token.testpypi ${POETRY_PYPI_TOKEN_PYPI}
      # - poetry install --no-root  # use for running tests
      - poetry build -f sdist
      - poetry publish -r testpypi
