---

kind: pipeline
type: docker
name: test

steps:
  - name: test-smoke
    image: python:3.6
    commands:
      - pip3 install poetry
      - poetry install --no-root
      - poetry run python3 -m doctest ./huntflow_py/*

  - name: publish-branches
    image: python:3.6
    environment:
      PYPI_TOKEN_TEST:
        from_secret: pypi_token_test
    commands:
      - pip3 install poetry
      - pip3 install --upgrade keyrings.alt
      - poetry config repositories.testpypi https://test.pypi.org/legacy/
      - poetry config pypi-token.testpypi $${PYPI_TOKEN_TEST}
      - poetry publish -n --build -r testpypi
    when:
      branch:
        exclude:
          - master

  - name: publish-master
    image: python:3.6
    environment:
      PYPI_TOKEN_PROD:
        from_secret: pypi_token_prod
    commands:
      - pip3 install poetry
      - pip3 install --upgrade keyrings.alt
      - poetry config repositories.pypi https://pypi.org/legacy/
      - poetry config pypi-token.pypi $${PYPI_TOKEN_PROD}
      - poetry publish -n --build -r pypi
    when:
      branch:
        include:
          - master
