---

kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: python:3.6
    environment:
      POETRY_PYPI_TOKEN_PYPI:
        from_secret: poetry_pypi_token
    commands:
      - pip install poetry
      - poetry config repositories.test https://test.pypi.org/project/huntflow-py
      - poetry install
      - poetry build
      - poetry publish
